version: '2'
services:
  web:
    build: .
    ports:
     - "8080:8080"
    volumes:
      - ./www:/var/www
    links:
     - appdb
    environment:
      LUCEE_PASSWORD: MakeThisSecretLuceeAdminPassword!
      MYSQL_ROOT_PASSWORD : MakeThisSecretMySQLRootPassword!
      MYSQL_HOST : appdb
      MYSQL_DATABASE : appdatabase
      BASE_APP_INSTALL: mura
  appdb:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD : MakeThisSecretMySQLRootPassword!
      MYSQL_DATABASE : appdatabase